version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.14.3
    working_directory: /go/src/github.com/flowerinthenight/kettle/
    steps:
    - checkout
    - run:
        name: build
        shell: /bin/bash
        command: |
          cd examples/simple/
          go build -v
